version: '2'
services:
  133003-traefik:
    image: traefik
    command: -c /dev/null --web --docker --docker.domain=dck.mojserver.mk
    labels:
      - "traefik.enable=false"
    ports:
      - "13380:80"
      - "13580:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  my-app:
    image: 133003/soa
    labels:
      - "traefik.port=8080"
      - "traefik.backend=133003-app"
      - "traefik.frontend.rule=Host:133003-app.dck.mojserver.mk"
    depends_on:
      - 133003-traefik

volumes:
  133003-datavolume: {}
